name: "CI Matrix Planner"
description: "Parses commit/PR message and labels to compute enabled jobs and targets"
runs:
  using: node20
  main: index.js  # or index.js if you ship raw + node_modules
branding:
  icon: grid     # Feather icon name: https://feathericons.com/
  color: blue    # One of: white, yellow, blue, green, orange, red, purple, gray, black
inputs:
  config-path:
    description: "Path to JSON config file in the consumer repo"
    required: false
    default: ".github/plan-ci.json"
  mode-input:
    description: "Override mode via workflow_dispatch (components|full)"
    required: false
    default: ""
  message-override:
    description: "Override message for debugging"
    required: false
    default: ""
  labels-override:
    description: "Comma-separated labels for debugging"
    required: false
    default: ""
  github-token:
    description: "GitHub token to allow reading PR commit messages via API"
    required: false
    default: ""
outputs:
  mode:
    description: "Resolved mode (components|full)"
  only_jobs:
    description: "Space-separated list of jobs explicitly requested (may be empty)"
  skip_jobs:
    description: "Space-separated list of jobs to skip (may be empty)"
  targets_json:
    description: "JSON array of targets to use in matrix"
  targets_list:
    description: "Space-separated list of targets"
  enabled_jobs:
    description: space-separated list of jobs that will run    

